-- =============================================================================
-- SUPERSEDED — no-op
-- This bootstrap migration has been superseded by the bounded-context
-- architecture defined in migrations 001–015. Those migrations run first
-- (lexicographic order) and own all schemas, enums, tables, and triggers
-- that were originally here.
-- =============================================================================
